# Demo of Self Attention in Pytorch 

In this Notebook we want to test, that Self-Attention and Piece wise Feed Forward Neural Networks can solve a simple logical, deterministic problem. Furthermore, we want to attest to the degree, that the attention weights can "explain" the predictions. We see that this is the case for Piece Wise Feed Forward Neural Netowrks but it is not! the case for Self Attention Neural Networks. We conjegture, that this is due to the fact that the representation of Self Attention is dependend on all elements of the input sequence

In [1]:
import random
import numpy as np
from model_pytorch import *
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset,sampler,DataLoader

import torch
import torch.nn as nn
from tensorboardX import SummaryWriter
from sklearn.metrics import roc_auc_score


In [2]:
#We generate list of range 
all_data=[]
all_label=[]
for j in range(100000):
    rand_list=[]
    for j in range(random.randint(1,100)):
        rand_list.append((random.randint(1,20),random.randint(1,20),random.random()))
    
    rand_list=np.array(rand_list)
    
    places_17_1=np.sum(rand_list[:,0:2]==[17, 1],axis=1)==2
    places_18_9=np.sum(rand_list[:,0:2]==[18, 9],axis=1)==2
     
    
    if (any(places_17_1) and any(places_18_9) and any(rand_list[places_17_1][:,2]>0.5)and any(rand_list[places_18_9][:,2]<0.5)):
        #We include this for mislabeling 
        all_label.append(1) 
    else:
        all_label.append(0)
        
    all_data.append(rand_list)

In [6]:
train_X,val_X,train_y,val_y = train_test_split(all_data, all_label, test_size=0.1, random_state=123)

In [7]:
class dummy_data(Dataset):
    def __init__(self, input,output):     
        
        self.data=input
        self.label=output
        
    def __len__(self):
        return int(len(self.data))
    
    def __getitem__(self, index):
        
        X=self.data[index]
        y=self.label[index]
        
        return X, y

In [8]:
train_ds=dummy_data(train_X,train_y)
val_ds=dummy_data(val_X,val_y)

In [9]:
batch_size=32

In [11]:
#THe collate deffines how data gets batched 

def my_collate(batch):
    
    texts=([x[0] for x in batch])
    labels=np.array(([x[1] for x in batch]))
    batch_size=len(batch)
    maxlen=np.max([len(x) for x in texts])
    text_stack=np.zeros(shape=(batch_size,maxlen,3))
    
    for enu,txt in enumerate(texts):
        text_stack[enu,0:len(txt),:]=txt

    return torch.tensor(text_stack[:,:,0]).cuda(),torch.tensor(text_stack[:,:,1]).cuda(),torch.tensor(text_stack[:,:,2]).cuda(),torch.tensor(labels).cuda()

In [12]:
val_dl= DataLoader(dataset=val_ds,
                      batch_size=batch_size,
                      shuffle=False,
                      collate_fn=my_collate
                      )

In [13]:
train_dl= DataLoader(dataset=train_ds,
                      batch_size=batch_size,
                      shuffle=True,
                      collate_fn=my_collate
                      )

In [22]:
class simple_fraud_model(nn.Module):
    def __init__(self, d_model=32,heads=1,nlay=1,dropout=0,SelfA=True,return_w=False):
        
        super(simple_fraud_model,self).__init__()
        self.return_w=return_w
        emb_d_1=int(d_model/2)
        emb_d_2=int(d_model/2)
        
        self.embedding_1=nn.Embedding(num_embeddings=21,embedding_dim=emb_d_1)
        self.embedding_2=nn.Embedding(num_embeddings=21,embedding_dim=emb_d_2-1)

        
        if SelfA==True:
            self.encoder_layers=EncoderLayer(d_model=d_model,heads=heads,dropout=dropout,share_params=True)

        if SelfA==False:
            self.encoder_layers=FeedForward(d_model)


        self.mula=multi_attention(input_dim=d_model,key_dim=d_model,nheads=1,return_weights=True,value_dim=d_model)

        self.fully_con=nn.Linear(d_model,d_model*2)
        self.relu=nn.ReLU()
        self.final_fully_con=nn.Linear(d_model*2,1)
        self.sig=nn.Sigmoid()
        self.selfa=SelfA
        
        
    def forward(self, x1,x2,x3,return_w):
        
        e1=self.embedding_1(x1)
        e2=self.embedding_2(x2)

        cat=torch.cat([e1,e2,x3.unsqueeze(2)],dim=2)
        if self.selfa==True:
            
            feat,w2=self.encoder_layers(cat)
        else:
            feat=self.encoder_layers(cat)

        ag,weights=self.mula(feat)
        fc=self.relu(self.fully_con(ag.squeeze()))
        preds=self.sig(self.final_fully_con(fc))
        if return_w==False:
            return preds.squeeze()
        if return_w==True:
            if self.selfa==True:
                #w2=w2.squeeze()
                #w2=w2.permute((0,2,1))
                #weights=torch.bmm(w2,weights)
                return preds.squeeze(),torch.bmm(w2.squeeze(),weights)
            else:
                return preds.squeeze(),weights

In [23]:
sf=simple_fraud_model(d_model=64,SelfA=False).cuda()

In [24]:
batch=next(iter(train_dl))

In [25]:
sf(batch[0].long(),batch[1].long(),batch[2].float(),False)

tensor([0.9525, 0.8354, 0.9743, 0.8289, 0.9388, 0.9793, 0.9597, 0.9782, 0.8659,
        0.9772, 0.9597, 0.9660, 0.8520, 0.8799, 0.9687, 0.8247, 0.9273, 0.9750,
        0.9523, 0.9218, 0.9754, 0.9797, 0.7633, 0.8099, 0.9723, 0.7238, 0.9753,
        0.9696, 0.9827, 0.8308, 0.9766, 0.9805], device='cuda:0',
       grad_fn=<SqueezeBackward0>)

In [30]:
#A train and evaluation funciton
def train_eval(atnm,train,opti,crit,eval_metrics,iterator,n_iter,writer):
    
    
    '''
    Args:
    atnm: A Model to be trained/evalued
    train: If we want to train/eval (If train we sub the gradient)
    opti: An optimizer to be used
    crit: A loss function to be used
    eval_matrics: If we want to keep track of predictions during batch gen and in the end
    calculate a metric on the whole data (aka the AUC)
    iterator: The data generator as an iterator
    n_iter: the current step to be updated
    writer: the tensorboard writer used to keep trakc of training results
    
    
    '''
    
    if train==False:
        loss_val=[]
        name1="val_loss"
        name2="val_roc"  
        atnm.eval()
    else:
        name1="train_loss"
        name2="train_roc"
        atnm.train()

    if eval_metrics:
        store_label=[]
        store_preds=[]
    #The epcoh 
    for batch in iterator:
        #print(batch[0].shape[1])
        opti.zero_grad()
        #batch=ba
        predictions=atnm(batch[0].long(),batch[1].long(),batch[2].float(),False)        #print(predictions)
        loss = crit(predictions, batch[3].float().cuda())

        if train==True:
            loss.backward()
            opti.step()
            n_iter=n_iter+1
            writer.add_scalar(name1,loss.cpu().detach().numpy(),n_iter)
        #when we dont train we dont write during epoch but only at the end
        #also we dont up the iter
        if train==False:
            loss_val.append(loss.cpu().detach().numpy())
        if eval_metrics== True: 
            store_preds.append(predictions.cpu().detach().numpy())
            store_label.append(batch[3].float().cpu().detach().numpy())
            
        del predictions
        del loss
### End of Batch
    if train == False:
        writer.add_scalar(name1,np.mean(loss_val),n_iter)

    if eval_metrics== True: 
        store_preds=np.concatenate(store_preds)
        store_label=np.concatenate(store_label)
        roc=roc_auc_score(store_label,store_preds)
        writer.add_scalar(name2,roc,n_iter)

        return roc

In [31]:
#we set up a model and we use a BCE Loss and Adam optimizer
sf=simple_fraud_model(SelfA=False,d_model=32).cuda()
criterion=nn.BCELoss()
optimizer = torch.optim.Adam(sf.parameters(), lr=5e-5)

In [32]:
#here we can use tensorboard to keep track of the training process 
writer = SummaryWriter(log_dir="logs/pff_noresidual__:____")

In [33]:
max_epochs=60

In [34]:
for j in range(max_epochs):
    #atnm,train,opti,crit,eval_metrics,iterator
    n_iter=(train_ds.__len__()/batch_size)*j
    roc_t=train_eval(sf,True,optimizer,criterion,True
                   ,iter(train_dl),n_iter=n_iter,writer=writer)
    roc_v=train_eval(atnm=sf
                     ,train=False
                     ,opti=optimizer
                     ,crit=criterion
                     ,eval_metrics=True
                     ,iterator=iter(val_dl)
                    ,writer=writer
                    ,n_iter=n_iter
                   )
    
    print(roc_v)

0.7506197943439853
0.7677331365672024
0.7794366747535523
0.7938223528095131
0.8337414713073631
0.867031113960595
0.8999413874667814
0.9423927950211592
0.9793395562519087
0.988203516372624
0.9903469520534304
0.9917676895091153
0.9936228046381672
0.9945124252879886
0.9953830774804577
0.9956429453461839
0.9957662403189735
0.9970807544134858
0.997617561756555
0.9987727408093083
0.999281095466349
0.9995144074917819
0.9996016623956023
0.9996661551506
0.9998691176442693
0.9996775362250114
0.9998804987186807
0.9999241261705909
0.9998596334155933
0.9999601662395602
0.9999791346969125
0.9999184356333852
0.9999886189255887
0.9999279198620613
0.9998729113357397
0.999965856776766
0.999975341005442
0.9999696504682364
0.9999905157713239
0.9999924126170591
0.9999032608675034
0.9999886189255885
0.9996851236079524
0.9999962063085296
0.999941197782208
0.9999639599310306
0.9999924126170591
0.9998975703302978
0.9999943094627943
0.999975341005442
0.9999905157713239
0.9999336103992671
0.9999487851651488
0.99

In [34]:
it=iter(val_dl)

# Explaining predictions

In this loop we show that the model correctly recovers the "reason" for a fraud prediction as being the existence of one of the touple of problematic input elements. Here Self Attention generally performs much better. 



In [35]:
for batch in it:
    #We get both inputs
    i1=batch[0].long()
    i2=batch[1].long()
    
    #We get both prediction and attention weights 
    predictions,weights=sf(i1,i2,batch[2].float(),True)
    #we put the predictions and weights to numpy, 
    preds_np=np.round(predictions.detach().cpu().numpy())
    weights_np=weights.detach().cpu().numpy()
    #We only select the elments we predicted as a 
    fraud_elem=np.where(preds_np>0.5)[0]
    #A prediction check, that we are correct
    if fraud_elem.size>0:
        if not(all(fraud_elem == np.where(batch[3].cpu().numpy())[0])) : 
            print("predicted wrong")
            break
        #if len(np.where(fraud_elem))>0:
        i1=i1.detach().cpu().numpy()
        i2=i2.detach().cpu().numpy()   

        for fraud_ele in fraud_elem:
            my_weight=np.squeeze(np.round(weights_np[fraud_ele],2))
            in_elem=np.stack([np.squeeze(i2[fraud_ele]),np.squeeze(i1[fraud_ele])],axis=1)

            atn_elem=np.where(my_weight>0.5)[0]
            in_elem_j=in_elem[atn_elem]

            print(in_elem_j)



[[ 9 18]
 [ 9 18]
 [ 9 18]]
[[ 9 18]
 [ 9 18]
 [ 1 17]
 [ 9 18]]
predicted wrong
